? из файнали подавит из кэтч
будет обработано в finally блоке. Если было выброшено два исключения – одно в try, второе в 
finally, то исключение в finally “проглотит” исключение выше (см. пример). Если до блока finally 
исключение было обработано, то мы можем получить информацию об исключении в блоке try и тем 
самым не потерять исключение, которое впоследствии может быть перезаписано в finally другим 
исключением